fields:
  domain:
    name: Domain
  progress:
    name: Progress
  status:
    name: Status
    options:
      FAIL: Backlog
      OK: Done
      WARN: In progress
  subtasks:
    name: Subtasks
project:
  enabled: true
  number: null
  owner: iMAGRAY
  repo: PSQL_SSH_API_MCP
  type: repository
  workers: 0
